version: '2.2'
services:
  django:
    volumes:
      - '.:/usr/src/sc'
      - '/home/ubuntu/backup:/backup'
    environment:
      DEBUG: 'False'
      GEONODE_LB_HOST_IP: 2c.puerti.co
      GEONODE_LB_PORT: 80
      SITEURL: https://2c.puerti.co/
      ALLOWED_HOSTS: "['2c.puerti.co', 'localhost']"
      GEOSERVER_PUBLIC_LOCATION: https://2c.puerti.co/gs/
      GEOSERVER_WEB_UI_LOCATION: https://2c.puerti.co/geoserver/

  celery:
    environment:
      DEBUG: 'False'
      GEONODE_LB_HOST_IP: 2c.puerti.co
      GEONODE_LB_PORT: 80
      SITEURL: https://2c.puerti.co/
      ALLOWED_HOSTS: "['2c.puerti.co', ]"
      GEOSERVER_PUBLIC_LOCATION: https://2c.puerti.co/gs/
      GEOSERVER_WEB_UI_LOCATION: https://2c.puerti.co/geoserver/

  geoserver:
    environment:
      GEONODE_LB_HOST_IP: 2c.puerti.co
      GEONODE_LB_PORT: 80
      NGINX_BASE_URL: https://2c.puerti.co/
